# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: ['pull_request', 'push']

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          1.8,  # Minimum supported by Minecraft
          11,   # Current Java LTS
          15    # Latest version
        ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      # Test
      - name: Build
        run: ./gradlew build
      # Release
      - name: Read mod version
        id: mod_version
        # Only Release builds from LTS Java on one OS when pushing
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'mod_version'
      - name: Read Minecraft version
        id: minecraft_version
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'minecraft_version'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        uses: anothrNick/github-tag-action@1.26.0
        id: tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: ${{ steps.mod_version.outputs.value }}
          DEFAULT_BUMP: patch
      - name: Create release
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        uses: actions/create-release@v1.1.4
        id: releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tags.outputs.new_tag }}
          release_name: Corntopia ${{ steps.tags.outputs.new_tag }} (alpha)
          body: \*\*For Minecraft ${{ steps.minecraft_version.outputs.value }}\*\*
          draft: true
          prerelease: true
      - name: Attach artifacts
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.releases.outputs.upload_url }}
          asset_path: ./build/libs/corntopia-${{ steps.mod_version.outputs.value }}-dev.jar
          asset_name: corntopia-${{ steps.tags.outputs.new_tag }}-alpha.jar
          asset_content_type: application/java-archive
